services:
  runner:
    build:
      context: ./Docker Image
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    deploy:
      mode: replicated
      replicas: 8
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M
    group_add:
      # Run echo DOCKER_GID=$(stat -c '%g' /var/run/docker.sock) >> .env in the host
      - "${DOCKER_GID}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
