services:
  runner:
    build:
      context: ./Docker Image
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    deploy:
      mode: replicated
      replicas: 8
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M
