version: "3.8"

services:
  runner:
    image: custom-github-runner-mac:latest
    platform: linux/arm64
    restart: always
    environment:
      - REPO=<owner>/<repo>
      - REG_TOKEN=<reg-token-for-self-hosted-runner>
      - NAME=<runner-name>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
